project:
  type: website

website:
  title: "first-ish principle"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/xiaochuany
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css
execute:
  freeze: auto
