project:
  type: website

website:
  title: "Xiaochuan's blog"
  navbar:
    right:
      - text: about
        href: https://xiaochuany.github.io/omega/
      - icon: github
        href: https://github.com/xiaochuany
      - icon: linkedin
        href: https://www.linkedin.com/in/xiaochuan-yang-088975188/
      - icon: twitter
        href: https://twitter.com/xiaochuandev
      - href: https://www.youtube.com/@xiaochuanyang
        icon: youtube
      - href: index.xml
        icon: rss
  site-url: https://xiaochuany.github.io/1principle
  description: "Xiaochuan's blog: first principles first"

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
