project:
  type: website

website:
  title: "first-ish principle"
  navbar:
    right:
      - text: about
        href: https://xiaochuany.github.io/omega/
      - icon: github
        href: https://github.com/xiaochuany
      - icon: linkedin
        href: https://www.linkedin.com/in/xiaochuan-yang-088975188/
      - href: https://www.youtube.com/@xiaochuanyang
        icon: youtube

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
